version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":ghost: "

  # Maintain dependencies for Cargo.toml
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":ghost: "
  
  # Maintain dependencies for NPM
  - package-ecosystem: "npm"
    directory: "/server/ui"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":ghost: "
    allow:
      - dependency-name: "@patternfly/*"
        dependency-type: "direct"
