use chrono::NaiveDate;
use xbuilder::prelude::*;

use crate::common::{assert_voided_documents, proveedor_base};

mod common;

const BASE: &str = "tests/resources/e2e/renderer/voideddocument/VoidedDocumentsTest";

#[serial_test::serial]
#[tokio::test]
async fn voided_document() {
    let mut doc = VoidedDocuments {
        numero: 1,
        fecha_emision: NaiveDate::from_ymd_opt(2022, 1, 31),
        fecha_emision_comprobantes: NaiveDate::from_ymd_opt(2022, 1, 29),
        proveedor: proveedor_base(),
        comprobantes: vec![
            VoidedDocumentsItem {
                tipo_comprobante: Some("01"),
                serie: "F001",
                numero: 1,
                descripcion_sustento: "Mi sustento1",
            },
            VoidedDocumentsItem {
                tipo_comprobante: Some("01"),
                serie: "F001",
                numero: 2,
                descripcion_sustento: "Mi sustento2",
            },
        ],
        ..Default::default()
    };

    assert_voided_documents(&mut doc, &format!("{BASE}/voidedDocument.xml")).await;
}

#[serial_test::serial]
#[tokio::test]
async fn voided_document_auto_generated_tipo_comprobante() {
    let mut doc = VoidedDocuments {
        numero: 1,
        fecha_emision: NaiveDate::from_ymd_opt(2022, 1, 31),
        fecha_emision_comprobantes: NaiveDate::from_ymd_opt(2022, 1, 29),
        proveedor: proveedor_base(),
        comprobantes: vec![
            VoidedDocumentsItem {
                serie: "F001",
                numero: 1,
                descripcion_sustento: "Mi sustento1",
                ..Default::default()
            },
            VoidedDocumentsItem {
                serie: "F001",
                numero: 2,
                descripcion_sustento: "Mi sustento2",
                ..Default::default()
            },
        ],
        ..Default::default()
    };

    assert_voided_documents(
        &mut doc,
        &format!("{BASE}/voidedDocument_autoGeneratedTipoComprobante.xml"),
    )
    .await;
}

#[serial_test::serial]
#[tokio::test]
async fn voided_document_auto_generated_fecha_emision() {
    let mut doc = VoidedDocuments {
        numero: 1,
        fecha_emision_comprobantes: NaiveDate::from_ymd_opt(2019, 12, 22),
        proveedor: proveedor_base(),
        comprobantes: vec![
            VoidedDocumentsItem {
                serie: "F001",
                numero: 1,
                descripcion_sustento: "Mi sustento1",
                ..Default::default()
            },
            VoidedDocumentsItem {
                serie: "F001",
                numero: 2,
                descripcion_sustento: "Mi sustento2",
                ..Default::default()
            },
        ],
        ..Default::default()
    };

    assert_voided_documents(
        &mut doc,
        &format!("{BASE}/voidedDocument_autoGeneratedFechaEmision.xml"),
    )
    .await;
}
