[package]
name = "xsigner"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Sign your XML files"

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
rsa = { workspace = true }
rand = { workspace = true }
rcgen = { workspace = true }
x509-parser = { workspace = true }

[dev-dependencies]
