version: '3'
services:
  postgres:
    image: docker.io/library/postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "ublhub"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d ublhub" ]
      interval: 10s
      timeout: 5s
      retries: 5
