[package]
name = "openubl-oidc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.5.2", features = ["derive", "env"]}
serde = { version = "1.0.193", features = ["derive"] }
