//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ubl_document")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub file_id: String,
    pub supplier_id: String,
    pub identifier: String,
    pub r#type: String,
    pub voided_document_code: Option<String>,
    pub digest_value: Option<String>,
    pub sha256: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
