//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "keystore_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub val: String,
    pub keystore_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::keystore::Entity",
        from = "Column::KeystoreId",
        to = "super::keystore::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Keystore,
}

impl Related<super::keystore::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Keystore.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
