name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      - name: Install clippy
        run: rustup component add clippy
      - run: cargo fmt --check
      - run: cargo check
      - run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test

  ui-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Verify package-lock.json
        working-directory: openubl/ui
        run: ./scripts/verify_lock.mjs
      - name: Install
        working-directory: openubl/ui
        run: npm clean-install --ignore-scripts
      - name: Lint sources
        working-directory: openubl/ui
        run: npm run lint
      - name: Build
        working-directory: openubl/ui
        run: npm run build
      - name: Test
        working-directory: openubl/ui
        run: npm run test -- --coverage --watchAll=false
