name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

env:
  CI: true

jobs:
  test:
    name: JDK ${{matrix.java-version}} JVM Tests
    strategy:
      matrix:
        java-version: [ 17 ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
          cache: maven
      - name: Build with Maven
        run: mvn verify

  quarkus-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -Pnative install
      - name: Build with Maven
        run: mvn -Pnative-image install -f quarkus-extension/integration-tests/

  quarkus-supported-v:
    needs: [ quarkus-extension ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        quarkus-version: [ 3.0.1.Final, 3.2.2.Final, 3.3.2 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Maven tests
        run: mvn -Pnative install
      - name: Maven IT tests
        run: mvn -Pnative-image install -f quarkus-extension/integration-tests/ -Dquarkus.version=${{ matrix.quarkus-version }}