name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

env:
  CI: true

jobs:
  linux-jvm-tests:
    name: JDK ${{matrix.java-version}} JVM Tests
    strategy:
      matrix:
        java-version: [ 11, 17 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
      - name: Build with Maven
        run: mvn verify
