name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

env:
  CI: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ../actions/install-dependencies
      - name: Install clippy
        run: rustup component add clippy
      - run: cargo fmt --check
      - run: cargo check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test
