name: PR Checks

on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify PR contents
    steps:
      - name: Check Title
        id: verifier
        uses: project-openubl/release-tools/cmd/verify-pr@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
