name: Master branch

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  code-scan:
    name: Code Scan
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'project-openubl' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
      - name: Build with Maven and Coverage/Sonar
        run: mvn verify -P coverage,sonar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Codecov metrics
        uses: codecov/codecov-action@v2

  early-access:
    name: Early access
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'project-openubl' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 11
      - name: Deploy to GitHub
        run: mvn deploy -Pgithub
        env:
          GITHUB_TOKEN: ${{ github.token }}
