pub mod anticipos;
pub mod descuentos;
pub mod detraccion;
pub mod direccion_entrega;
pub mod forma_de_pago;
pub mod percepcion;
pub mod tipo_comprobante;
pub mod tipo_operacion;
pub mod total_importe;
